parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/*/Domain/'
            - '../src/Shared/Domain/'

    App\Identity\Domain\Repository\UserRepositoryInterface:
        class: App\Identity\Infrastructure\Persistence\DoctrineUserRepository

    App\Project\Domain\Repository\ProjectRepositoryInterface:
        class: App\Project\Infrastructure\Persistence\DoctrineProjectRepository
